### ISSUE TITLE
缺失数据集

### ISSUE THREAD

**Issue by 77camellia** [icmpnorequest/ICASSP2024_ASTHL#1]
Gowalla缺失数据集
NYV和TKY顺利跑通，Gowalla下缺失3个文件

报错：FileNotFoundError: [Errno 2] No such file or directory: 'datasets/Gowalla/train_poi_zero.txt'

**Comment by icmpnorequest** [comment]
Hi, maybe you could try deal with Gowalla dataset as described in the paper. We cannot upload the dataset for the size issue.
